language: php

matrix:
  exclude:
    - php: 5.6
      env: LARAVEL_VERSION=5.5.* TESTBENCH_VERSION=3.5.*

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION=5.4.* TESTBENCH_VERSION=3.4.* PHPUNIT_VERSION=5.7.*
  - LARAVEL_VERSION=5.5.* TESTBENCH_VERSION=3.5.*

before_script:
  - composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}" "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update; fi;
  - composer update
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
